GET https://api-dev.domecompass.com/people/50
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxIiwic3ViIjoyMTcsImF1ZCI6IioiLCJ0eXBlIjoidXNlciIsImlhdCI6MTYyOTA5NDg3OSwibmJmIjoxNjI5MDk0ODc5LCJleHAiOjE2MjkzNTQwNzl9.LFBvaODwqWMHnw1bvTVgSPeLFSbUI8s70I4T8X78cwY
